<?php
// Plugin definition
$plugin = array(
  'title' => t('Accordion with 10 Regions'),
  'icon' => 'ten_accordion.png',
  'category' => t('OpenHSU'),
  'theme' => 'ten_accordion',
  'regions' => array(
    'column-one' => t('Content One'),
    'column-two' => t('Content Two'),
    'column-three' => t('Content Three'),
    'column-four' => t('Content Four'),
    'column-five' => t('Content Five'),
    'column-six' => t('Content Six'),
    'column-seven' => t('Content Seven'),
    'column-eight' => t('Content Eight'),
    'column-nine' => t('Content Nine'),
    'column-ten' => t('Content Ten'),
    'column-eleven' => t('Content Eleven'),
    'column-twelve' => t('Content Twelve'),
    'column-thirteen' => t('Content Thirteen'),
    'column-fourteen' => t('Content Fourteen'),
    'column-fifteen' => t('Content Fifteen'),
    'column-sixteen' => t('Content Sixteen'),
    'sidebar' => t('Sidebar'),
  ),
);
