<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_preprocess_carousel().
 */
function hsu_carousel_preprocess_carousel(&$vars) {
  // Output a class on the carousel to indentify which style was chosen.
  $fpp_wrapper = entity_metadata_wrapper('fieldable_panels_pane', $vars['entity_id']);
  $vars['classes_array'][] = drupal_html_class($fpp_wrapper->field_hot_bs_carousel_style->value());
}