<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_preprocess_carousel().
 */
function hsu_carousel_preprocess_carousel(&$vars) {
  // Output a class on the carousel to indentify which style was chosen.
  $style = hsu_carousel_get_field_value('field_hsu_carousel_style', $vars['entity_id']);
  $vars['classes_array'][] = drupal_html_class($style);
  
  // Check whether the slideshow should autoplay or not.
  $autoplay = hsu_carousel_get_field_value('field_hsu_carousel_autoplay', $vars['entity_id']);
  if (!$autoplay) {
    // We want to turn off autoplay. This is happening by virtue of 
    // data-ride="carousel" on the wrapping div.
    unset($vars['attributes_array']['data-ride']);
  }
  
  // Add some custom css.
  $path = drupal_get_path('module', 'hsu_carousel');
  drupal_add_css($path . '/css/hsu_carousel.css');
  
}

/**
 * Implements hook_preprocess_carousel_slide().
 */
function hsu_carousel_preprocess_carousel_slide(&$vars) {
  // Load wrappers for the fieldable panel pane and the slide field collections.
  $entity_type = 'field_collection_item';
  $fpp_wrapper = entity_metadata_wrapper('fieldable_panels_pane', $vars['fpp_id']);
  $fc_wrapper = entity_metadata_wrapper($entity_type, $vars['fc_id']);

  // Set the picture mapping depending on what style was chosen for this 
  // carousel.
  switch ($fpp_wrapper->field_hsu_carousel_style->value()){
    // Image full width, text over-layed.
    case 'img_12_text_over':
      $picture_mapping = 'kalapicture_12';
      break;  
    
    // Image half width, text to the left.
    case 'img_6_text_left':
      $picture_mapping = 'kalapicture_6';
      break;
  }
  
  // Set up the picture formatter display settings using the correct picture 
  // mapping.
  $display = array(
    'label' => 'hidden',
    'type' => 'picture',
    'settings' => array(
      'picture_mapping' => $picture_mapping,
      'fallback_image_style' => 'large',
      'image_link' => '',
    ),
  );
  
  $vars['image'] = field_view_field($entity_type, $fc_wrapper->value(), 'field_hot_bs_carousel_s_img', $display);
}

/**
 * Implements hook_preprocess_carousel_controls().
 */
function hsu_carousel_preprocess_carousel_controls(&$vars){
  // Add template suggestion for each style. 
  $style = hsu_carousel_get_field_value('field_hsu_carousel_style', $vars['entity_id']);
  $vars['theme_hook_suggestions'][] = 'carousel_controls__' . $style;
}

/**
 * Get the given field value for the given FPP.
 * This extra layer is needed to avoid errors in preview when a field doesn't
 * exist yet.
 */
function hsu_carousel_get_field_value($field_name, $fpp_id){
  $fpp_wrapper = entity_metadata_wrapper('fieldable_panels_pane', $fpp_id);
  return $fpp_wrapper->__isset($field_name) ? $fpp_wrapper->{$field_name}->value() : '';
}

/**
 * Implements hook_theme_registry_alter().
 */
function hsu_carousel_theme_registry_alter(&$registry) {
  $path = drupal_get_path('module', 'hsu_carousel') . '/templates';
  $registry += drupal_find_theme_templates($registry, '.tpl.php', $path);  
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function hsu_carousel_form_fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form_alter(&$form, &$form_state, $form_id){
  // So we did a bunch of work to add custom carousel styles but now we we only
  // want one, so rather than remove the fields, logic and styling, I'm leaving
  // it in and just hiding it from the user. This way we can add custom style
  // options back in by removing these two lines.
  $form['field_hsu_carousel_style'][LANGUAGE_NONE]['#default_value'] = 'img_6_text_left';
  $form['field_hsu_carousel_style']['#access'] = FALSE;
}
