<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_preprocess_carousel().
 */
function hsu_carousel_preprocess_carousel(&$vars) {
  // Output a class on the carousel to indentify which style was chosen.
  $style = hsu_carousel_get_carousel_style($vars['entity_id']);
  $vars['classes_array'][] = drupal_html_class($style);
  
  // Add some custom css.
  $path = drupal_get_path('module', 'hsu_carousel');
  drupal_add_css($path . '/css/hsu_carousel.css');
  
}

/**
 * Implements hook_preprocess_carousel_slide().
 */
function hsu_carousel_preprocess_carousel_slide(&$vars) {
  // Load wrappers for the fieldable panel pane and the slide field collections.
  $entity_type = 'field_collection_item';
  $fpp_wrapper = entity_metadata_wrapper('fieldable_panels_pane', $vars['fpp_id']);
  $fc_wrapper = entity_metadata_wrapper($entity_type, $vars['fc_id']);

  // Set the picture mapping depending on what style was chosen for this 
  // carousel.
  switch ($fpp_wrapper->field_hot_bs_carousel_style->value()){
    // Image full width, text over-layed.
    case 'img_12_text_over':
      $picture_mapping = 'kalapicture_12';
      break;  
    
    // Image half width, text to the left.
    case 'img_6_text_left':
      $picture_mapping = 'kalapicture_6';
      break;
  }
  
  // Set up the picture formatter display settings using the correct picture 
  // mapping.
  $display = array(
    'label' => 'hidden',
    'type' => 'picture',
    'settings' => array(
      'picture_mapping' => $picture_mapping,
      'fallback_image_style' => 'large',
      'image_link' => '',
    ),
  );
  
  $vars['image'] = field_view_field($entity_type, $fc_wrapper->value(), 'field_hot_bs_carousel_s_img', $display);
}

/**
 * Implements hook_preprocess_carousel_controls().
 */
function hsu_carousel_preprocess_carousel_controls(&$vars){
  // Add template suggestion for each style. 
  $style = hsu_carousel_get_carousel_style($vars['entity_id']);
  $vars['theme_hook_suggestions'][] = 'carousel_controls__' . $style;
}

/**
 * Get the carousel style chosen for the given FPP.
 */
function hsu_carousel_get_carousel_style($fpp_id){
  $fpp_wrapper = entity_metadata_wrapper('fieldable_panels_pane', $fpp_id);
  return $fpp_wrapper->__isset('field_hot_bs_carousel_style') ? $fpp_wrapper->field_hot_bs_carousel_style->value() : '';
}

/**
 * Implements hook_theme_registry_alter().
 */
function hsu_carousel_theme_registry_alter(&$registry) {
  $path = drupal_get_path('module', 'hsu_carousel') . '/templates';
  $registry += drupal_find_theme_templates($registry, '.tpl.php', $path);
}